'use client';
import Absences from './absences';
import {useState} from 'react';
import type {State,Command} from '@/operations/lib/operations/model';
import {timeHours,type Timesheet} from '@/operations/lib/operations/timesheets';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/operations/components/ui/dialog';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/operations/components/ui/table';
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Los_Angeles',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const time=(v:string|null)=>v?new Date(v).toLocaleTimeString('en-US',{timeZone:'America/Los_Angeles',hour:'numeric',minute:'2-digit'}):'Still open';
export default function Timesheets({data,save,busy}:{data:State;save:(c:Command,close?:boolean)=>Promise<boolean>;busy:boolean}){
 const [from,setFrom]=useState(()=>today().slice(0,7)+'-01'),[to,setTo]=useState(today),[employee,setEmployee]=useState(''),[status,setStatus]=useState('all'),[selected,setSelected]=useState<Timesheet|null>(null),[notes,setNotes]=useState('');
 const rows=data.timesheets.filter(t=>t.date>=from&&t.date<=to&&(!employee||t.employeeId===employee)&&(status==='all'||t.status===status)).sort((a,b)=>b.date.localeCompare(a.date));
 const names=Array.from(new Map(data.timesheets.map(t=>[t.employeeId,t.employeeName])).entries());
 async function review(status:string){if(selected&&await save({type:'extension',action:'reviewTimesheet',value:{id:selected.id,status,notes}},false))setSelected(null);}
 return <><section className="panel account-section"><div className="flex-between"><h2>Staff submissions</h2><span className="chip">Staff portal not connected</span></div><p>GMZ Staff will supply time entries here after staff accounts and property assignments are connected. No staff hours have been imported.</p><div className="exp-actions"><a className="btn secondary" href="#field">Field map & routes</a><a className="text-button" href="#schedule">Office schedule →</a></div></section>
 <div className="toolbar"><label className="field"><span>From</span><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="field"><span>Through</span><input type="date" min={from} value={to} onChange={e=>setTo(e.target.value)}/></label><label className="field"><span>Staff member</span><select value={employee} onChange={e=>setEmployee(e.target.value)}><option value="">All staff</option>{names.map(([id,name])=><option value={id} key={id}>{name}</option>)}</select></label><label className="field"><span>Status</span><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option value="pending">Pending review</option><option value="approved">Approved</option><option value="rejected">Returned for correction</option></select></label></div>
 {from>to?<p role="alert">Choose an end date on or after the start date.</p>:<section className="panel account-section"><div className="flex-between"><h2>Time entries</h2><button className="btn" disabled={busy||!rows.some(t=>t.status==='pending'&&t.clockOut)} onClick={()=>{const t=rows.find(t=>t.status==='pending'&&t.clockOut);if(t){setSelected(t);setNotes(t.notes)}}}>Review & approve</button></div><p className="muted">{rows.length} entries · {rows.filter(t=>t.status==='pending').length} pending review · Times shown in Pacific time</p><Table><TableHeader><TableRow>{['Staff / date','Property','Clock in','Clock out','Break','Recorded hours','Status','Review'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map(t=><TableRow key={t.id}><TableCell>{t.employeeName}<small className="block">{t.date}</small></TableCell><TableCell>{data.properties.find(p=>p.id===t.propertyId)?.name||'Unassigned'}</TableCell><TableCell>{time(t.clockIn)}</TableCell><TableCell>{time(t.clockOut)}</TableCell><TableCell>{t.breakMinutes} min</TableCell><TableCell>{timeHours(t)??'Open shift'}</TableCell><TableCell>{t.status==='rejected'?'Returned':t.status}</TableCell><TableCell>{t.status!=='approved'&&<button className="btn secondary" disabled={busy||!t.clockOut} onClick={()=>save({type:'extension',action:'reviewTimesheet',value:{id:t.id,status:'approved',notes:t.notes}},false)}>Approve</button>}<button className="text-button" onClick={()=>{setSelected(t);setNotes(t.notes)}}>Review entry</button></TableCell></TableRow>)}</TableBody></Table>{!rows.length&&<div className="empty"><h3>{data.timesheets.length?'No entries match these filters':'No staff submissions yet'}</h3><p>{data.timesheets.length?'Adjust the date, staff member, or status filters.':'Approve becomes available when a completed staff timesheet is submitted. Scheduled visits and vehicle trips are not counted as staff hours.'}</p></div>}<p className="muted">Hours are submitted time less recorded breaks. This screen does not calculate wages or run payroll.</p></section>}
 <Absences data={data} save={save} busy={busy}/>
 <Dialog open={!!selected} onOpenChange={v=>!v&&setSelected(null)}><DialogContent className="editor"><DialogHeader><DialogTitle>Review timesheet</DialogTitle><DialogDescription>{selected?.employeeName} · {selected?.date}</DialogDescription></DialogHeader><label className="field"><span>Review note / reason for return</span><textarea maxLength={4000} value={notes} onChange={e=>setNotes(e.target.value)}/></label><div className="exp-actions"><button className="btn" disabled={busy||!selected?.clockOut} onClick={()=>review('approved')}>Approve</button><button className="btn secondary" disabled={busy||!notes.trim()} onClick={()=>review('rejected')}>Return for correction</button><button className="text-button" disabled={busy} onClick={()=>review('pending')}>Reopen review</button></div></DialogContent></Dialog></>;
}
